import styles from "../styles/layout.module.css";
import Header from "../components/Header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={styles.container}>
        <div className={styles.layoutWrapper}>
          <Header />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
